global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Net.Http;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using Lumui.Client;
global using LumuiProtocol = Lumui.Client.LumuiProtocol;
global using Lumui.Cli.Views;
global using Terminal.Gui.App;
global using Terminal.Gui.Configuration;
global using Terminal.Gui.Input;
global using Terminal.Gui.ViewBase;
global using Terminal.Gui.Views;
global using TerminalAttribute = Terminal.Gui.Drawing.Attribute;
global using TerminalColor = Terminal.Gui.Drawing.Color;
global using TerminalScheme = Terminal.Gui.Drawing.Scheme;
